# ~/.config/starship.toml
#
# Run in zsh to see palette of available colors:
# for i in {0..255}; do print -Pn "%K{$i} %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done

# Refresh
#eval "$(starship init bash)"
#
#    ~   󰈙      🔑     
# end_left: =   
# end_right: =   
#
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Disable the blank line at the start of the prompt
add_newline = true

# =========prompt=========

format = """
[        ](bg:lcars_blue)
[        ](bg:lcars_blue)\
[](fg:lcars_blue)
[](fg:lcars_blue)\
[ ](bg:lcars_blue)\
[         ](bg:lcars_blue)\
[($status)](bg:lcars_blue)\
[$character](bg:lcars_blue)\
[ ](bg:lcars_blue)\
[ ]()\
[ $sudo](bg:lcars_graytan)\
[ ]()\
[ ${custom.files}${custom.directories}](bg:lcars_tan)\
[ ]()\
[ $battery](bg:lcars_gold)\
[ ]()\
[ ($cmd_duration)](fg:#000000 bg:lcars_orange)\
[ ]()\
$os\
[](fg:lcars_brown)
[ ]()
[](fg:lcars_blue)\
$env_var\
$username\
$hostname\
$localip\
[ ]()\
[](fg:#000000 bg:lcars_graytan)\
$directory\
[ ]()\
[ ](fg:#000000 bg:lcars_tan)\
$git_branch\
$git_status\
$git_commit\
$git_state\
$git_metrics\
$fossil_branch\
$fossil_metrics\
$hg_branch\
$pijul_channel\
$vcsh\
[ ]()\
[ ](fg:#000000 bg:lcars_gold)\
$buf\
$bun\
$c\
$cmake\
$cobol\
$conda\
$crystal\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$gradle\
$haxe\
$helm\
$haskell\
$java\
$julia\
$kotlin\
$lua\
$meson\
$mise\
$mojo\
$nats\
$nim\
$nix_shell\
$nodejs\
$ocaml\
$odin\
$opa\
$package\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$red\
$rlang\
$ruby\
$scala\
$rust\
$spack\
$swift\
$terraform\
$typst\
$vagrant\
$vlang\
$xmake\
$zig\
[ ]()\
[ ](fg:#000000 bg:lcars_orange)\
$aws\
$azure\
$docker_context\
$gcloud\
$guix_shell\
$kubernetes\
$openstack\
$pixi\
$singularity\
[ ]()\
$time\
$shell$shlvl$jobs\
[ ](fg:lcars_brown)
[        ](bg:lcars_blue)\
[](fg:lcars_blue)
[        ](bg:lcars_blue)
"""
#$time

# A continuation prompt that displays filled-in arrow
continuation_prompt = "[        ](bg:lcars_blue)"

# Disable the blank line at the start of the prompt
# add_newline = false

# =========palettes=========

# Set "foo" as custom color palette
palette = "foo"

# Define custom colors
[palettes.foo]

# Define new color
#lcars_purple = "purple"
lcars_blue = "blue"
lcars_tan = "#FFAA90"
lcars_gold = "yellow"
lcars_orange = "bright-yellow"
lcars_brown = "red"
#lcars_grayblue = "#774477"
lcars_graytan = "white"

# =======OS===========
#GhostBSD: replace $os with \U000f02a0 󰊠

[os]
format = "[ $symbol ]($style)"
style = "fg:#ffffff bg:lcars_brown"
disabled = false

[os.symbols]
AIX = "➿ "
Alpaquita = " " #alpaca
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " " #
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
#GhostBSD = "󰊠 "
HardenedBSD = "󰞌 "
Illumos = " "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "#🌿
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = " " #󰈺
OpenCloudOS = ''
openEuler = ''
openSUSE = " "
OracleLinux = " " #󰌷 ⊂⊃
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
RockyLinux = " "
Solus = "󰠳 " #
SUSE = " "
Ubuntu = " "
Ultramarine = "󰼮 "
Unknown = " "
Void = " "
Windows = " " #

# ==========battery========

[battery]
full_symbol = "󰂃 "
charging_symbol = "⚡️ "
discharging_symbol = "󰁽 "
empty_symbol = '󰂎 '
format = "[$symbol$percentage]($style)"
disabled = false

# [[battery.display]]
# threshold = 25
# style = "bold fg:fg_red2 bg:lcars_gold"

# [[battery.display]]
# threshold = 50
# style = "bold fg:orange bg:lcars_gold"

# [[battery.display]]
# threshold = 75
# style = "bold fg:yellow bg:lcars_gold"

[[battery.display]]
threshold = 100
style = "fg:black bg:lcars_gold"
# style = "bold fg:green bg:lcars_gold"

# ==========sudo========

[sudo]
symbol = "🔑"
style = "fg:#000000 bg:lcars_graytan"
disabled = false

# ==========status========

[cmd_duration] #    
format='[ $duration]($style)'
style='fg:#000000 bg:lcars_orange'

[character]
success_symbol = "[](bold fg:green bg:lcars_blue)" # ✅
error_symbol = "[✘](bold fg:red bg:lcars_blue)" # ⛔
format = "[$symbol](bg:bg_6)"

[status]
disabled = false
format = '[\[$status:$common_meaning\] ](fg:red bg:lcars_blue)'

# =========user/host=========

[env_var.STY]
#variable = 'STY'
style = "fg:#000000 bg:#86BBD8"
format = "[  $env_value ]($style)"
# default=""
# disabled = true

[hostname]
ssh_only = true
style = "fg:#FFFFFF bg:lcars_blue"
format = "[ $hostname ]($style)"
trim_at = "-"
# disabled = true

[username]
show_always = true
style_user = "fg:#FFFFFF bg:lcars_blue"
style_root = "fg:#FFFFFF bold bg:lcars_blue"
format = '[ ($user) ]($style)' # 

[localip]
ssh_only = true
style = "fg:#FFFFFF bg:lcars_blue"
format = '[󰩠 $localipv4 ]($style)'
disabled = false

# ========directory==========

[directory]
style = "bg:lcars_graytan fg:#000000"
format = "[ $read_only $path ]($style)"
read_only = '󰌾 ' #🔒
#read_only_style   = ''
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
home_symbol=" " #🏠
use_os_path_sep = true

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 " # Doc
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "
"Projects" = "󰲋 "
".config" = ""
#"School" = "󰑴"
#"GitHub" = ""
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

# inspired by @lolbat on CodeBerg
[custom.files]
description = "Show files count for current directory"
command = "find ./ -maxdepth 1 -type f | wc -l"
format = "[ 󰈔 $output]($style)"
style = "fg:000000 bg:lcars_tan"
when = "true"

[custom.directories]
description = "Show directory count count for current directory"
command = "find ./ -maxdepth 1 -type d | tail -n +2 | wc -l"
format = "[  $output]($style)"
style = "fg:000000 bg:lcars_tan"
when = "true"

# =========src ctrl=========

[git_branch]
symbol = "" #              |
style = "fg:#000000 bg:lcars_tan"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#000000 bg:lcars_tan"
format = '[ $all_status$ahead_behind ]($style)'
conflicted = '󰞇= $count'
ahead = "⇡ $count "
behind = "⇣ $count "
deleted = "🗑 $count " #
diverged = "󰃻 $count " #
renamed = " $count "
stashed = "📦 $count "
modified = "󰙏 $count " #  
staged = " $count "
untracked = "󰙌 $count " # 🤷󰙌
up_to_date = '✓'

[git_commit]
disabled=true
only_detached=false
tag_disabled=false
tag_symbol = ' '
# tag_max_candidates=1
style = "bg:lcars_tan"
format = "[$symbol$hash$tag ]($style)"
commit_hash_length = 4

[git_state]
disabled=false
style = "bg:lcars_tan"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
cherry_pick = '[🍒 PICKING]'
rebase = '[ REBASING]'
merge = '[ MERGING]'
bisect = '[🔍 BISECTING]'
am = '[AM]'
am_or_rebase = '[AM/REBASE]'
revert = '[󰕍 REVERTING]'
#progress_divider = ' of '

[git_metrics]
added_style = "fg:#000000 bg:lcars_tan"
deleted_style = "fg:#000000 bg:lcars_tan"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
disabled = false

[fossil_branch]
symbol = '󰘬'
style = " fg:#000000 bg:lcars_tan"
format = '[ $symbol $branch ]($style)'

[hg_branch]
symbol = " "
style = " fg:#000000 bg:lcars_tan"
format = '[ $symbol $branch ]($style)'

[pijul_channel]
symbol = " "
style = " fg:#000000 bg:lcars_tan"
format = '[ $symbol $branch ]($style)'

[vcsh]
symbol = '󰘬'
style = " fg:#000000 bg:lcars_tan"
format = '[ $symbol $branch ]($style)'

# ========toolchains/packages==========

# [ansible]
# symbol = "Ⓐ "
# style = "fg:black bg:lcars_gold"
# format = '[$symbol $version ]($style)'

[buf]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[bun]
symbol = ''
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[c]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[cmake]
symbol = ''
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[cobol]
symbol = '⚙️'
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[conda]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[crystal]
symbol = ''
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[daml]
symbol = '𝜦'
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[dart]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[deno]
symbol = '' #🦕
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[dotnet]
symbol = "󰪮 " # 
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[elixir]
symbol = " " #💧
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[elm]
symbol = " " #🌳
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[erlang]
symbol = ''
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[fennel]
symbol = '' #󰬍  󰬍
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[fortran]
symbol = '󱈚 ' # 
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[gleam]
symbol = 'GLEAM'
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[golang]
symbol = " " #🐹
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[gradle]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[haskell]
symbol = " " #λ
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[haxe]
symbol = " " #
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[helm]
symbol = ''
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[java]
symbol = "☕ "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[julia]
symbol = "ஃ " #
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[kotlin]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[lua]
symbol = " " #
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[meson]
symbol = "󰔷 " # M
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[mise]
symbol = "󰰏 "
#health = 'ready'
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[mojo]
symbol = 'MOJO'
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[nats]
symbol = "󰰒 "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[nim]
symbol = " " #👑
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[nix_shell]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[nodejs]
symbol = "󰎙 " #󰎙 🔷 
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[ocaml]
symbol = " "# 
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[odin]
symbol = 'ODIN'
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[opa]
symbol = ' ' #   
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[package]
disabled=false
symbol = "󰏗 " #  📦
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[perl]
symbol = " " #
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[php]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[pulumi]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[purescript]
symbol = ''
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[python]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[quarto]
symbol = 'QUARTO'
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[raku]
symbol = ' ' #
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[red]
symbol = 'RED'
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[rlang]
symbol = "󰟔 " # R
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[ruby]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[rust]
symbol = "" #🦀
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[scala]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[spack]
symbol = " " # S 🅢
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[swift]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[terraform]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[typst]
symbol = ''
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[vagrant]
symbol = ""
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[vlang]
symbol = ""
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[xmake]
symbol = "󰰰 " # 󰰲
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

[zig]
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[$symbol $version ]($style)'

# ========containers==========

[aws]
symbol = "  "
style = "bg:lcars_orange"
format = '[[ $symbol $context ](bg:lcars_orange)]($style) $path'

[azure]
symbol = " " # 󰠅
style = "bg:lcars_orange"
format = '[[ $symbol $context ](bg:lcars_orange)]($style) $path'

[docker_context]
symbol = "🐳 "
style = "bg:lcars_orange"
format = '[[ $symbol $context ](bg:lcars_orange)]($style) $path'

[gcloud]
disabled = false
symbol = "☁️ "
style = "bg:lcars_orange"
format = '[[ $symbol $context ](bg:bg_2)]($style) $path'

[guix_shell]
symbol = " "
style = "bg:lcars_orange"
format = '[[ $symbol $context ](bg:lcars_orange)]($style) $path'
disabled = false

[kubernetes]
format = '[ $context $namespace]($style) '
style = "bg:lcars_orange"
disabled = false

[openstack]
symbol = " "
style = "bg:lcars_orange"
format = '[[ $symbol $context ](bg:lcars_orange)]($style) $path'

[pixi]
symbol = "󰰘 " # 󰰚
style = "bg:lcars_orange"
format = '[[ $symbol $context ](bg:bg_2)]($style) $path'

[singularity]
disabled = false
style = "bg:lcars_orange"
format = '[󰯭 $context $namespace]($style) ' #AppTainer

# ========time/shell/shlvl/jobs==========

[time]
disabled = false
time_format = "%R" # Hour:Minute Format # %T for seconds
style = "bg:lcars_brown"
format = '[[  $time ](fg:#ffffff bg:lcars_brown)]($style)'

[shell]
disabled=false
bash_indicator = ''
fish_indicator='󰈺' #🐟
zsh_indicator="󰰶"
powershell_indicator = '' # 
cmd_indicator = ' ' #
ion_indicator = ''
elvish_indicator = "󰘧"
tcsh_indicator = "󰰤"
nu_indicator = "nu"
xonsh_indicator = "🐚" # seashell emoji
unknown_indicator = ' '
style = "fg:#ffffff bg:lcars_brown"
format="[ $indicator ]($style)" #space on right b/c double-width symbol

[shlvl]
disabled=false
symbol=""
style = "fg:#ffffff bg:lcars_brown"
format = '[ $symbol$shlvl]($style)'

[jobs]
disabled = false
symbol = ' '
number_threshold = 1
symbol_threshold = 1
style = "fg:#ffffff bg:lcars_brown"
format="[ $symbol$number]($style)"

[memory_usage]
disabled=true
symbol = " "
style = "fg:black bg:lcars_gold"
format = '[ $symbol ]($style)'
