XDG_CURRENT_DESKTOP=Hyprland
XDG_SESSION_TYPE=wayland
XDG_SESSION_DESKTOP=hyprland
GDK_BACKEND=wayland
QT_QPA_PLATFORM=wayland;xcb
QT_WAYLAND_SHELL_INTEGRATION=hypr
SDL_VIDEODRIVER=wayland
MOZ_ENABLE_WAYLAND=1
CLUTTER_BACKEND=wayland
ECORE_EVAS_ENGINE=wayland_egl
ELM_ENGINE=wayland_egl
