[Autologin]
Relogin=false
Session=
User=

[General]
Daemonize=true
GreeterEnvironment=QML_PLATFORM=wayland,QT_QPA_PLATFORM=wayland,SDL_VIDEODRIVER=wayland,XDG_CURRENT_DESKTOP=Hyprland,XDG_SESSION_TYPE=wayland
HaltCommand=/usr/bin/systemctl poweroff
InputMethod=
Numlock=none
RebootCommand=/usr/bin/systemctl reboot
Type=seat
WaylandEnable=true

[Security]
AllowRootLogin=false
DefaultSession=hyprland.desktop
DisableGreeter=false
HideShells=
HideUsers=
MaximumUid=60000
MinimumUid=1000
RememberLastUser=true
RememberPassword=false
SessionDir=/usr/share/xsessions:/usr/share/wayland-sessions
UserList=true

[Theme]
Current=breeze
CursorTheme=breeze_cursors
Font=Montserrat,10,-1,5,50,0,0,0,0,0
FullName=false
Gravity=Center
Icon=/usr/share/sddm/themes/breeze/icons/application-x-executable.svg
InputFont=Montserrat,10,-1,5,50,0,0,0,0,0
FacesDir=/usr/share/sddm/faces
Themed=/usr/share/sddm/themes/breeze
X11Drag=all
Background=/usr/share/backgrounds/sddm-gradient.png

[Users]
MaximumUid=60000
MinimumUid=1000
HideUsers=
ShowUsers=selected

[Wayland]
EnableHiDPI=true
SessionDir=/usr/share/wayland-sessions

[XServer]
Arguments=-dpi 96
Command=/usr/bin/X -core
HandleLid=true
Path=/usr/bin
ServerPath=/usr/bin/X
